version: '3'
services:
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
          - prometheus_data:/prometheus
#            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
#            - '-alertmanager.url=http://alertmanager:9093'
        ports:
            - '9090:9090'

    node-exporter:
        image: prom/node-exporter:v0.18.1
        ports:
            - '9100:9100'

    grafana:
        image: grafana/grafana:3.0.1
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
#    alertmanager:
#        image: prom/alertmanager:0.1.1
#        command:
#            - '-config.file=alertmanager.yml'

volumes:
    prometheus_data: {}
    grafana_data: {}
